version: '3'

services:
  discovery-server:
    image: danchuo/discovery-server:latest
    container_name: discovery-server-app
    ports:
      - "8761:8761"

  api-gateway:
    image: danchuo/api-gateway:latest
    container_name: api-gateway-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  skills-evaluation:
    image: danchuo/skills-evaluation:latest
    container_name: skills-evaluation-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-skills

  postgres-skills:
    image: postgres:latest
    container_name: skill-evaluations-postgres
    environment:
      - POSTGRES_DB=hse_db
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5432:5432"
