version: '3'

services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server-app
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  auth-service:
    build: ./auth-service
    container_name: auth-service-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-users

  skills-evaluation:
    build: ./skills-evaluation
    container_name: skills-evaluation-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-skills

  postgres-skills:
    image: 'postgres:latest'
    container_name: postgres-skills
    environment:
      - POSTGRES_DB=skills
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5432:5432"

  postgres-users:
    image: 'postgres:latest'
    container_name: postgres-users
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5433:5432"