version: '3'

services:
  discovery-server:
    image: danchuo/discovery-server:latest
    container_name: discovery-server-app
    ports:
      - "8761:8761"

  api-gateway:
    image: danchuo/api-gateway:latest
    container_name: api-gateway-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  auth-service:
    image: danchuo/auth-service:latest
    container_name: auth-service-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-users

  skills-evaluation:
    image: danchuo/skills-evaluation:latest
    container_name: skills-evaluation-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-skills

  profile-service:
    image: danchuo/profile-service:latest
    container_name: profile-service-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - api-gateway
      - postgres-profiles

  postgres-skills:
    image: postgres:latest
    container_name: postgres-skills
    environment:
      - POSTGRES_DB=skills
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5432:5432"

  postgres-users:
    image: 'postgres:latest'
    container_name: postgres-users
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5433:5432"

  postgres-profiles:
    image: 'postgres:latest'
    container_name: postgres-profiles
    environment:
      - POSTGRES_DB=profiles
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=hsepassword
    ports:
      - "5434:5432"
