name: Deploy to docker hub

on:
  pull_request:
    types: [ closed ]

jobs:
  build_and_push:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-gateway, discovery-server, skills-evaluation, auth-service, profile-service ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build project with maven
        run: mvn -B clean package --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine version of the module
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ${{ matrix.service }}/pom.xml)
          echo "::set-output name=version::$VERSION"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            danchuo/${{ matrix.service }}:${{ steps.get_version.outputs.version }}
            danchuo/${{ matrix.service }}:latest
